### ISSUE TITLE
Upgrade to Puppet4?

### ISSUE THREAD

**Issue by jtlisi** [voxpupuli/puppet-prometheus#34]
Would it be possible to refactor the code to be puppet 4 compatible sooner rather than later? From what I understand puppet3 modules are going out of [support](https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/) soon. I would be open to putting in a PR and the branching the module in it's current state on the puppet3 branch.

**Comment by brutus333** [comment]
Hello!
We are in the process of transferring the repo. Due to my mistake (I forked the repo instead of transferring it) now the last version of the module with all changes is hosted on https://github.com/bastelfreak/puppet-prometheus2, waiting someone from voxpupuli admins to approve the request of switching the root of fork network.
So please refer to https://github.com/bastelfreak/puppet-prometheus2 for a while.
Virgil
